import Navbar from "@/components/Navbar";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { fetcher } from "../api/fetcher";
import Head from 'next/head'

export default function Page(){
    const router = useRouter();
    // console.log(router.query.bookname)
    const bookname = router.query.bookname;
    // console.log("bookname is "+bookname)
    // console.log("router.query.bookname is "+router.query.bookname)
    const [Data,SetData] = useState(null);
    useEffect(()=>{
        // console.log("bookname is"+bookname)
        fetcher('../api/getbook/'+bookname).then((e)=>{
          SetData(e)
        })
      },[bookname])

  
    // console.log(Data);
    return (
        <>
            <Head>
                <title>{bookname}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" type="image/png" href="https://www.mebmarket.com/web/assets/images/ico/favicon-32x32.png"/>
            </Head>
            <Navbar/>
            {/* {Data} */}
        </>
    )
}