import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { fetcher } from "../api/fetcher";
import Head from 'next/head'
import { Button } from "@mui/material";
import RatingAbleCustomizedRating from "@/components/RatingAbleCustomizedRating";
import AccountCircleIcon from '@mui/icons-material/AccountCircle';
import { TextField } from "@mui/material";
import RecentComment from "@/components/RecentComment";
import CustomizedRating from "@/components/CustomRating";
import { useSession } from "next-auth/react";



export default function Page() {
    const { data: clientSession, status } = useSession()
    const router = useRouter();
    const [Data, SetData] = useState(null);
    const [ratingGiven, setRatingGiven] = useState(0)
    const [commentWriten, setcommentWriten] = useState("")
    const bookname = router.query.bookname;

    const UploadComment = () => {
        
    }

    useEffect(() => {
        const fetchData = async () => {
            const e = await fetcher('../api/getBookByName/' + bookname);
            SetData(e);
            console.log(e);
        };
        if (bookname) {
            fetchData();
        }
    }, [bookname]);



    return (
        <>
            <Head>
                <title>{bookname}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" type="image/png" href="https://www.mebmarket.com/web/assets/images/ico/favicon-32x32.png" />
            </Head>
            {(Data != null) ?
                <div className="book_bookname_Container">
                    <div className="book_bookname_PageAdjust">
                        <h1 className="book_bookname_Bookname">{Data.bookname}</h1>
                        <div className="book_book_ItemAndDetail">
                            <img src={Data.cover} className="book_Img" />
                            <div id="Detail">
                                <div id="data_author_publisher_category">
                                    <p>โดย <a href={"/search/author/" + Data.author}>{Data.author}</a></p>
                                    <p>สำนักพิมพ์ <a href="">//ยังไม่มีสำนักพิมพ์</a></p>
                                    <p>หมวดหมู่ <a href="">//ยังไม่มี Catagory</a></p>
                                </div>
                                <div id="TryAndBuyDiv">
                                    <Button variant="contained" size="large" id="Try_Button">ทดลองอ่าน</Button>
                                    <Button variant="contained" size="large" className="Buy_Button">ซื้อ {Data.price} บาท</Button>
                                </div>
                                <div id="RatingZone" >
                                    <h5>{Data.rating}</h5>
                                    <CustomizedRating size="large" rate={Data.rating} />
                                </div>
                                <div id="release_date">
                                    <p>วันที่วางขาย</p>
                                    <p>{Data.date.substring(0, 10)}</p>
                                </div>
                            </div>
                        </div>
                        <div className="synopsis">
                            <p>
                                {Data.synopsis}
                            </p>
                        </div>
                        <div className="comment-section">
                            <div>
                                <h3>คอมเมนต์และให้เรตติ้ง</h3>
                            </div>
                            <div className="comment-profile-user">
                                <AccountCircleIcon fontSize="large" />
                                <div className="comment-show-username">
                                    <p>{!!clientSession ? clientSession.user.name:null}</p>
                                    {/* <Button
                                        className="login-register-button"
                                        variant="contained"
                                        size="small"
                                        onClick={handleClick}
                                    >
                                        {!clientSession ? ('ล็อคอินเข้าสู่ระบบ / สมัครสมาชิก') : clientSession.user.name}
                                    </Button> */}
                                </div>
                            </div>
                            <div className="rating-and-comment">
                                <div className="give-rate-zone">
                                    <RatingAbleCustomizedRating rate={ratingGiven || ""} onChange={(e) => {
                                        setRatingGiven(e)
                                    }} />
                                </div>
                                <div>
                                    <TextField type="text" value={commentWriten} onChange={(e) => { setcommentWriten(e.target.value) }} fullWidth className="comment-zone"
                                        multiline minRows={4} maxRows={4} placeholder="เขียนคอมเมนต์" />
                                </div>
                            </div>
                            <div className="comment-button">
                                <Button onClick={() => {
                                    UploadComment();
                                }} variant="contained" className="comment-submit">คอมเมนต์</Button>
                            </div>
                            <div className="all-comment">
                                <div className="all-comment-header">
                                    <h3>คอมเมนต์ทั้งหมด</h3>
                                </div>
                                <div className="recent-comment">
                                    <RecentComment />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                : null}

            {/* {Data} */}
        </>
    )
}