import { useRouter } from "next/router";
import Head from "next/head";
import { useState,useEffect } from "react";
import Navbar from "@/components/Navbar";
import InputLabel from '@mui/material/InputLabel';
import MenuItem from '@mui/material/MenuItem';
import FormControl from '@mui/material/FormControl';
import Select from '@mui/material/Select';
import { fetcher } from "../../api/fetcher";


export default function SearchPage(){
    const [SelectTab,setSelectTab] = useState("bookname");
    const router = useRouter();
    // console.log(router)
    const [Searchword,setSearchword] = useState(router.query.search)
    useEffect(()=>{
    },[])
    
    const [Type,setType] = useState()
    const handleChange = (e)=>{
        setSelectTab(e.target.value)
    }
    return (
        <>
            <Head>
                <title>test</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" type="image/png" href="https://www.mebmarket.com/web/assets/images/ico/favicon-32x32.png"/>
            </Head> 
                <Navbar/>
                <div className='CenterChild'>
                <div className="App">
                <div className='ItemsBox'>
                    <div className="NewestText">
                        <h2>
                            ค้นหาในร้านหนังสือ
                        </h2>
                    </div>
                    <div className="SearchArea">
                        <FormControl sx={{maxWidth:250}} fullWidth size="small" className="TypeSearch">
                            {/* <InputLabel id="demo-simple-select-label" size="small">hello</InputLabel> */}
                            <Select 
                            // variant="standard"
                            defaultValue="bookname"
                            labelId="demo-simple-select-label"
                            id="demo-simple-select"
                            value={SelectTab}
                            onChange={handleChange}
                            >
                            <MenuItem value={"bookname"}>ชื่อหนังสือ</MenuItem>
                            <MenuItem value={"author"}>นักเขียน</MenuItem>
                            <MenuItem value={"publisher"}>สำนักพิมพ์</MenuItem>
                            </Select>
                        </FormControl>
                        <div className="Searchline"/>
                        <form onSubmit={(e)=>{
                            e.preventDefault();
                        }}>
                            <input type="text" placeholder="ค้นหา" id="SearchInput" className="SearchBarInSearchPage"/>
                        </form>
                    </div>
                    {Searchword}
                    {SelectTab}
                    {Searchword!="default"?
                    <h2>Searchword is not default</h2>
                    :
                    <h2>Searchword is default</h2>
                    }
                </div>
                </div>
                </div>
        </>
    );
}