import { useRouter,Router } from "next/router";
import Head from "next/head";
import { useState,useEffect } from "react";
import Navbar from "@/components/Navbar";
import SearchIcon from '@mui/icons-material/Search';
export default function SearchPage(){
    const [RouterConst,setRouterConst] = useState(null);
    const [Search,setSearch] = useState("");
    const router = useRouter();
    // const 
    // console.log(router.query)
    useEffect(()=>{
        if(router.query.search!=="iconClicked"){
            setRouterConst(router.query.search);
        }
    },[router])
    useEffect(()=>{

    },[RouterConst])
    return (
        <>
            <Head>
                <title>test</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" type="image/png" href="https://www.mebmarket.com/web/assets/images/ico/favicon-32x32.png"/>
            </Head> 
                <Navbar/>
                <div className='CenterChild'>
                    <div className="App">
                        <div className='ItemsBox'>
                            <div className="NewestText">
                                <h2>
                                    ค้นหาในร้านหนังสือ
                                </h2>
                            </div>
                        <form className="formInSearchPage" onSubmit={(e)=>{
                            alert("hi");
                            e.preventDefault();
                        }}>
                            <input type="text" placeholder="ค้นหา" className="SearchBarInSearchPage"/>
                        </form>

                        </div>
                    </div>
                </div>
        </>
    );
}