import { useRouter } from "next/router";
import Head from "next/head";
import { useState,useEffect } from "react";
import Navbar from "@/components/Navbar";

export default function Search(){
    const [Search,setSearch] = useState(null);
    const router = useRouter();
    console.log(router.query)
    useEffect(()=>{
        setSearch(router.query.search);
    },[])
    // const router = useRouter();
    // console.log(router.query);
    return (
        <>
            <Head>
                <title>test</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" type="image/png" href="https://www.mebmarket.com/web/assets/images/ico/favicon-32x32.png"/>
            </Head> 
                <Navbar/>
        </>
    );
}