import Navbar from "@/components/Navbar";
import { TextField } from "@mui/material";
import Head from "next/head";
import {Button} from "@mui/material";
import AuthorAutocomplete from "@/components/AuthorAutocomplete";
import { useEffect, useRef, useState } from "react";
export default function addbook() {
    const [ImgLink,setImgLink] = useState("https://s3-us-west-2.amazonaws.com/s.cdpn.io/387928/book%20placeholder.png")
    const [author,setAuthor] = useState([]) //นักเขียน
    const TempImg = useRef(0)
    return (
        <>
            <Head>
                <title>meb: เพิ่มหนังสือ</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" type="image/png" href="https://www.mebmarket.com/web/assets/images/ico/favicon-32x32.png"/>
            </Head>
            <>
                <Navbar/>
                <div className="book_bookname_Container">
                    <div className="book_bookname_PageAdjust">
                        <TextField size="large" label="ชื่อหนังสือ" sx={{width:500}} />
                        <div    className="book_book_ItemAndDetail">
                            <img src={ImgLink} className="book_Img"/>
                            <div id="Detail">
                                <div id="data_author_publisher_category">
                                    <div className="addbook_input_feild">
                                        <p>ภาพหน้าปก</p>
                                        <form onSubmit={(e)=>{
                                            e.preventDefault();
                                            (TempImg.current && 1)? setImgLink(TempImg.current):
                                            setImgLink("https://s3-us-west-2.amazonaws.com/s.cdpn.io/387928/book%20placeholder.png")}}
                                            > {/*ใส่ภาพลงใน useState ImgLink*/}
                                            
                                            <TextField size="small" label="Url Image" onChange={(e)=>{TempImg.current = e.target.value }}/>
                                            <Button variant="contained" type="submit" className="Submit_Button">ยืนยัน</Button>
                                        </form>
                                        <p>นักเขียน</p>
                                        <AuthorAutocomplete onChange={e=>setAuthor(e)}
                                        /> 
                                    </div>
                                    {/* <p>สำนักพิมพ์ <a href="">//ยังไม่มีสำนักพิมพ์</a></p>
                                    <p>หมวดหมู่ <a href="">//ยังไม่มี Catagory</a></p> */}
                                </div>
                                {/* <div id="TryAndBuyDiv">
                                    <Button variant="contained" size="large" id="Try_Button">ทดลองอ่าน</Button>
                                    <Button variant="contained" size="large" id="Buy_Button">บาท</Button>
                                </div> */}
                                {/* <div id="RatingZone" >
                                    <h5>{Data.rating}</h5>
                                    <RatingAbleCustomizedRating  rate={Data.rating}/>
                                </div> */}
                                {/* <div id="release_date">
                                    <p>วันที่วางขาย</p>
                                    <p>// test</p>
                                </div> */}
                            </div>
                        </div>
                        <div className="synopsis">
                            <TextField
                                className="MultilineTextFeild"
                                id="outlined-multiline-flexible"
                                label="เนื้อเรื่องย่อ"
                                multiline
                                maxRows={6}
                            />
                        </div>
                    </div>
                </div>
            </>

        </>
    )
}