import * as React from 'react';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import MenuBookIcon from '@mui/icons-material/MenuBook';
import CommentIcon from '@mui/icons-material/Comment';
import { fetcher } from './api/fetcher';
import RecentCommentAllbook from '@/components/RecentCommentAllbook';
import PersonIcon from '@mui/icons-material/Person';
import Head from 'next/head';

export async function getStaticProps(context) {
    const BookCount = await fetcher("http://localhost:3000/api/getcount");
    const UsersCount = await fetcher("http://localhost:3000/api/getcountuser")
    const RecentComment = await fetcher("http://localhost:3000/api/getrecentComment")
    return {
        props: { BookCount, UsersCount, RecentComment }, // will be passed to the page component as props
    }
}

export default function admindashboard({ BookCount, UsersCount, RecentComment }) {
    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    type="image/png"
                    href="https://www.mebmarket.com/web/assets/images/ico/favicon-32x32.png"
                />
            </Head>
            <div className="dashboard-container">
                <Card sx={{ height: 250, width: 450 }} className="cardbox">
                    <CardContent>
                        <MenuBookIcon className='dashboard-icon' />
                    </CardContent>
                    <div className="dashboard-text">
                        <h2>หนังสือ</h2>
                        <h4>จำนวนหนังสือทั้งหมด</h4>
                        <h3>{BookCount}</h3>
                    </div>
                </Card>
                <Card sx={{ height: 250, width: 450 }} className="cardbox">
                    <CardContent>
                        <PersonIcon className='dashboard-icon' />
                    </CardContent>
                    <div className="dashboard-text">
                        <h2>User</h2>
                        <h4>จำนวน User ทั้งหมด</h4>
                        <h3>{UsersCount}</h3>
                    </div>
                </Card>
                <Card sx={{ width: 1000 }} className="cardbox dashboard-comment">
                    <CardContent className="dashboard-comment-header">
                        <CommentIcon fontSize='large' className='commentbox-icon' />
                        <h2>คอมเมนต์ล่าสุด</h2>
                    </CardContent>
                    <div className="dashboard-text-comment">
                        {Object.values(RecentComment).map((property, index) => {
                            return (<RecentCommentAllbook className="dashboard-comment-items" key={index} property={property} />)
                        })}
                    </div>
                </Card>
            </div>
        </>
    )
}
