import { useState } from "react";
import { getSession } from "next-auth/react";
import Head from "next/head";
import LibraryBook from "@/components/LibraryBook";

export async function getServerSideProps(context) {
    const res = await getSession(context);
    const username = res.user.name;
    const bookData = [
        {
            bookname: "Poon",
            bookId: 15,
            author: "retid",
            cover: "https://pbs.twimg.com/media/FqahQU_aUAAsVT7?format=jpg&name=4096x4096",
        },
        {
            bookname: "ไรเดนทวินเทล",
            bookId: "21",
            author: 20,
            cover: "https://pbs.twimg.com/media/Fq-_1WMaMAAjLfJ?format=jpg&name=small",
        },
        {
            bookname: "ลูแมว",
            bookId: "31",
            author: "Repoon",
            cover: "https://pbs.twimg.com/media/FpiO4nmaEAAti8l?format=jpg&name=small",
        },
    ];
    return {
        props: { username, bookData },
    };
}
export default function name({ username, bookData }) {
    // console.log(username);
    // console.log(bookData);
    const mapping = Object.values(bookData).map((data, index) => {
        return <LibraryBook property={data} key={index} />;
    });
    return (
        <>
            <Head>
                <title>ชั้นหนังสือ</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    type="image/png"
                    href="https://www.mebmarket.com/web/assets/images/ico/favicon-32x32.png"
                />
            </Head>
            <main>
                <div className="Shelf-items">{mapping}</div>
            </main>
        </>
    );
}
