import { useState } from "react";
import { getSession } from "next-auth/react";
import Head from "next/head";
import LibraryBook from "@/components/LibraryBook";

export async function getServerSideProps(context) {
    const res = await getSession(context);
    const username = res.user.name;
    const bookData = await fetch("http://localhost:3000/api/getPaidBook", {
        method: "POST",
        headers: {
            "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({
            username: username,
        }),
    }).then(e=>e.json())
    return {
        props: { username, bookData },
    };
}
export default function name({ username, bookData }) {
    // console.log(username);
    // console.log(bookData);
    const mapping = Object.values(bookData).map((data, index) => {
        return <LibraryBook property={data} key={index} />;
    });
    return (
        <>
            <Head>
                <title>ชั้นหนังสือ</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    type="image/png"
                    href="https://www.mebmarket.com/web/assets/images/ico/favicon-32x32.png"
                />
            </Head>
            <main>
                <div className="Shelf-items">{mapping}</div>
            </main>
        </>
    );
}
