import React, { useMemo } from "react";
import { useEffect, useState, useCallback } from "react";
import { fetcher } from "./api/fetcher";
import Loading from "@/components/Loading";
import Head from "next/head";
import ItemSmall from "@/components/ItemSmall";
import { Pagination } from "@mui/material";

export async function getStaticProps() {
    const initialBooks = await fetch(`http://localhost:3000/api/SortByRecent/1`).then(res => res.json());
    const count = await fetch("http://localhost:3000/api/getcount").then(res => res.json());
    return {
        props: {
            initialBooks,
            count: Math.ceil(count * 0.1),
        },
    };
}

export default function recentaddedpage({ initialBooks, count }) {
    const [books, setBooks] = useState(initialBooks);
    const ItemSmallMemoized = React.memo(ItemSmall);
    const [loading, setLoading] = useState(true);
    const [Page, setPage] = useState(1)

    const handleChange = useCallback((event, value) => {
        window.scrollTo(0, 0);
        setPage(value);
    }, []); 

    useEffect(() => {
        async function fetchData() {
            setLoading(true);
            const newBooks = await fetcher(`/api/SortByRecent/${Page}`);
            setBooks(newBooks);
            setLoading(false);
        }
        fetchData();
    }, [Page]);

    const bookElements = books.map((book, index) => (
        <ItemSmallMemoized key={`${book.bookId}-${index}`} property={book} />
    ));

    return (
        <>
            <Head>
                <title>meb: สินค้ามาใหม่ </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link
                    rel="icon"
                    type="image/png"
                    href="https://www.mebmarket.com/web/assets/images/ico/favicon-32x32.png"
                />
            </Head>
            <div className="sub-content-container">
                <div className="header-sub-content-container">
                    <h2>สินค้ามาใหม่</h2>
                </div>
                <div className="ImPagination"><Pagination size="large" count={count} page={Page || ""} onChange={handleChange} /></div>
                {loading ? (
                    <>
                        <Loading />
                    </>
                ) : (
                    <>
                        <div className="content-large-container">{bookElements}</div>
                        <div className="ImPagination"><Pagination size="large" count={count} page={Page || ""} onChange={handleChange} /></div>
                    </>
                )}
            </div>
        </>
    )
}