import React, { useMemo } from "react";
import { useEffect, useState } from "react";
import { fetcher } from "./api/fetcher";
import Loading from "@/components/Loading";
import Head from "next/head";
import ItemSmall from "@/components/ItemSmall";

export default function trendingpage() {
    const ItemSmallMemoized = React.memo(ItemSmall);
    const [TrendingItems, setTrendingItems] = useState([]);
    const [loading, setLoading] = useState(true);

    const fetchData = async () => {
        const data = await Promise.all([fetcher("/api/getRecentAddedPage")]);
        return data;
    }

    useEffect(() => {
        fetchData().then(([data]) => {
            setTrendingItems(data);
            setLoading(false)
        });
    }, []);

    const TrendingItemsMapped = useMemo(() => {
        return TrendingItems.map((property, index) => {
            return (
                <ItemSmallMemoized key={`${property.bookId}-${index}`} property={property} />
            );
        });
    }, [TrendingItems]);

    if (loading) {
        return <Loading />;
    }

    return (
        <>
            <Head>
                <title>meb: สินค้ามาแรง </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link
                    rel="icon"
                    type="image/png"
                    href="https://www.mebmarket.com/web/assets/images/ico/favicon-32x32.png"
                />
            </Head>
            <div className="sub-content-container">
                <div className="header-sub-content-container">
                    <h2>สินค้ามาแรง</h2>
                </div>
                <div className="content-large-container">{ TrendingItemsMapped }</div>
            </div>
        </>
    )
}