import React, { useMemo } from "react";
import { useEffect, useState } from "react";
import { fetcher } from "./api/fetcher";
import { useSession } from "next-auth/react";
import Head from "next/head";
import ItemSmall from "@/components/ItemSmall";
import Loading from "@/components/Loading";

export default function trendingpage() {
    const { data: session, status } = useSession();
    const ItemSmallMemoized = React.memo(ItemSmall);
    const [TrendingItems, SetTrending] = useState([])
    const loading = status === "loading";

    useEffect(() => {
        Promise.all([fetcher("/api/getBookByRatingPage")]).then(
        ([TrendingItems]) => {
            SetTrending(TrendingItems);
        }
        );
    }, []);

    const TrendingItemsMapped = useMemo(() => {
        return TrendingItems.map((property, index) => {
            return (
                <ItemSmallMemoized
                key={`${property.bookId}-${index}`}
                property={property}
                />
            );
            });
        }, [TrendingItems]);

    if (loading) {
        return <Loading />;
        }
        
    return (
        <>
            <Head>
                <title>meb: e-book ร้านอีบุ๊กจีนแดงอันดับ 1 </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link
                rel="icon"
                type="image/png"
                href="https://www.mebmarket.com/web/assets/images/ico/favicon-32x32.png"
                />
            </Head>
            <div className="sub-content-container">
                <div className="header-recent-container">
                <h2>สินค้ามาแรง</h2>
                </div>
                <div className="content-large-container">{ TrendingItemsMapped }</div>
            </div>
        </>
    )
}