import { requireAuthentication } from "@/utils/requireAuthentication";
import Head from "next/head";
import UserEdit from "@/components/UserEdit";

export default function UserEditPage({ data }) {
    const userdata = data;
    console.log(userdata);
    const mapped = Object.values(userdata).map((property, index) => {
        return <UserEdit property={property} key={index} />;
    });
    return (
        <>
            <Head>
                <title>จัดการผู้ใช้</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    type="image/png"
                    href="https://www.mebmarket.com/web/assets/images/ico/favicon-32x32.png"
                />
            </Head>
            <h1>test</h1>
            {mapped}
        </>
    );
}

export async function getServerSideProps(context) {
    const data = [
        { username: "adray", email: "adray@hentai.com" },
        { username: "fuse", email: "fuse@gmail.com" },
        { username: "poon", email: "poon@gay.com" },
    ];
    return requireAuthentication(context, ({ session }) => {
        return {
            props: { session, data },
        };
    });
}
