import { requireAuthentication } from "@/utils/requireAuthentication";
import Head from "next/head";
import UserEdit from "@/components/UserEdit";
import { fetcher } from "../api/fetcher";
export default function UserEditPage({ data }) {
    const userdata = data;
    console.log(userdata);

    const mapped = Object.values(userdata).map((property, index) => {
        return <UserEdit property={property} key={index} />;
    });

    return (
        <>
            <Head>
                <title>จัดการผู้ใช้</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    type="image/png"
                    href="https://www.mebmarket.com/web/assets/images/ico/favicon-32x32.png"
                />
            </Head>
            <h1>test</h1>
            <div className="user-edit-wrap">
                <div className="user-edit-container">{mapped}</div>
            </div>
        </>
    );
}

export async function getServerSideProps(context) {
    const response = await fetch("http://localhost:3000/api/user/getUser", {
        method: "POST",
        headers: {
            "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({
            amount: 5,
            page: 1,
        }),
    });
    const data = await response.json();
    return requireAuthentication(context, ({ session }) => {
        return {
            props: { session, data },
        };
    });
}
