import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Head from "next/head";
import CartItem from "@/components/CartItems";
import { CheckBox } from "@mui/icons-material";
import { Button } from "@mui/material";
import Link from "next/link";
// need security!
export default function Cart() {
    const router = useRouter();
    const username = router.query.username;
    const tempData = [
        {
            bookname: "Poon",
            cover: "https://pbs.twimg.com/media/FdMNYFkWAAAxu4k.jpg",
            price: 60,
        },
        {
            bookname: "notPoon",
            cover: "https://pbs.twimg.com/media/FdMNYFkWAAAxu4k.jpg",
            price: 56,
        },
        {
            bookname: "isPoon",
            cover: "https://pbs.twimg.com/media/FdMNYFkWAAAxu4k.jpg",
            price: 560,
        },
    ];
    const [checkedItems, setCheckedItems] = useState(
        Array(tempData.length).fill(true)
    );
    const [itemPrices, setItemPrices] = useState(
        Array(tempData.length)
            .fill(0)
            .map((price, index) => {
                return checkedItems[index] ? tempData[index].price : 0;
            })
    );

    const handleCheckboxChange = (index) => {
        const newCheckedItems = [...checkedItems];
        newCheckedItems[index] = !newCheckedItems[index];
        setCheckedItems(newCheckedItems);

        const newItemPrices = [...itemPrices];
        newItemPrices[index] = newCheckedItems[index]
            ? tempData[index].price
            : 0;
        setItemPrices(newItemPrices);
    };
    // useEffect( async () => {
    //     const response = await fetch('/api/cart/');
    //     const data = await response.json();
        
    // },[])
    const totalPrice = itemPrices.reduce((acc, cur) => acc + cur, 0);
    return (
        <>
            <Head>
                <title>ตะกร้า</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    type="image/png"
                    href="https://www.mebmarket.com/web/assets/images/ico/favicon-32x32.png"
                />
            </Head>
            <h1 className="cart-header">ตะกร้า</h1>
            <div className="center-cart-items">
                <div className="Cart-Items-container">
                    {Object.values(tempData).map((property, index) => {
                        return (
                            <li className="Items-row" key={index}>
                                <input
                                    type="checkbox"
                                    checked={checkedItems[index]}
                                    onChange={() => {
                                        handleCheckboxChange(index);
                                    }}
                                />
                                {/* <CheckBox value={property.price}/> */}
                                <CartItem property={property} />
                            </li>
                        );
                    })}
                </div>
                <Link href="/">
                    <h5 className="select-other-book">เลือกหนังสือเล่มอื่นต่อ</h5>
                </Link>
            </div>
            <div className="totalPrice-wrap">
                <div className="display-totalPrice">
                    <h3>ยอดชำระ ฿{totalPrice}</h3>
                    <Button variant="contained" size="medium" className="purchase">
                        ชำระเงิน
                    </Button>
                </div>
            </div>
        </>
    );
}
